// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be regenerated by build_runner

part of 'course_model.dart';

CourseModel _$CourseModelFromJson(Map<String, dynamic> json) => CourseModel(
  courseId: json['course_id'] as String,
  title: json['title'] as String,
  description: json['description'] as String,
  price: (json['price'] as num).toDouble(),
  currency: json['currency'] as String,
  imageUrl: json['image_url'] as String?,
);

Map<String, dynamic> _$CourseModelToJson(CourseModel instance) => <String, dynamic>{
  'course_id': instance.courseId,
  'title': instance.title,
  'description': instance.description,
  'price': instance.price,
  'currency': instance.currency,
  'image_url': instance.imageUrl,
};
