// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be regenerated by build_runner

part of 'order_model.dart';

OrderModel _$OrderModelFromJson(Map<String, dynamic> json) => OrderModel(
  id: json['id'] as String,
  currency: json['currency'] as String,
  amount: json['amount'] as int,
  receipt: json['receipt'] as String?,
);

Map<String, dynamic> _$OrderModelToJson(OrderModel instance) => <String, dynamic>{
  'id': instance.id,
  'currency': instance.currency,
  'amount': instance.amount,
  'receipt': instance.receipt,
};
