// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be regenerated by build_runner

part of 'transaction_model.dart';

TransactionModel _$TransactionModelFromJson(Map<String, dynamic> json) => TransactionModel(
  razorpayPaymentId: json['razorpay_payment_id'] as String,
  razorpayOrderId: json['razorpay_order_id'] as String,
  razorpaySignature: json['razorpay_signature'] as String?,
  status: json['status'] as String,
  courseId: json['course_id'] as String,
  amount: json['amount'] as int,
  currency: json['currency'] as String,
  userId: json['user_id'] as String,
  email: json['email'] as String?,
);

Map<String, dynamic> _$TransactionModelToJson(TransactionModel instance) => <String, dynamic>{
  'razorpay_payment_id': instance.razorpayPaymentId,
  'razorpay_order_id': instance.razorpayOrderId,
  'razorpay_signature': instance.razorpaySignature,
  'status': instance.status,
  'course_id': instance.courseId,
  'amount': instance.amount,
  'currency': instance.currency,
  'user_id': instance.userId,
  'email': instance.email,
};
