// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be regenerated by build_runner
// Run: flutter pub run build_runner build --delete-conflicting-outputs

part of 'auth_state.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

mixin _$AuthState {
  @optionalTypeArgs
  TResult when<TResult extends Object?>({
    required TResult Function() initial,
    required TResult Function() loading,
    required TResult Function(User user) authenticated,
    required TResult Function() unauthenticated,
    required TResult Function(String message) error,
  }) => throw UnimplementedError();

  @optionalTypeArgs
  TResult? whenOrNull<TResult extends Object?>({
    TResult? Function()? initial,
    TResult? Function()? loading,
    TResult? Function(User user)? authenticated,
    TResult? Function()? unauthenticated,
    TResult? Function(String message)? error,
  }) => throw UnimplementedError();

  @optionalTypeArgs
  TResult maybeWhen<TResult extends Object?>({
    TResult Function()? initial,
    TResult Function()? loading,
    TResult Function(User user)? authenticated,
    TResult Function()? unauthenticated,
    TResult Function(String message)? error,
    required TResult orElse(),
  }) => throw UnimplementedError();
}

class _Initial implements _Initial {
  const _Initial();
}

class _Loading implements _Loading {
  const _Loading();
}

class _Authenticated implements _Authenticated {
  const _Authenticated(this.user);
  
  @override
  final User user;
}

class _Unauthenticated implements _Unauthenticated {
  const _Unauthenticated();
}

class _Error implements _Error {
  const _Error(this.message);
  
  @override
  final String message;
}
