// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be regenerated by build_runner

part of 'tenant_mapping_model.dart';

TenantMappingModel _$TenantMappingModelFromJson(Map<String, dynamic> json) => TenantMappingModel(
  userId: json['user_id'] as String,
  tenantId: json['tenant_id'] as String,
  role: json['role'] as String,
  email: json['email'] as String,
  createdAt: json['created_at'] as String?,
);

Map<String, dynamic> _$TenantMappingModelToJson(TenantMappingModel instance) => <String, dynamic>{
  'user_id': instance.userId,
  'tenant_id': instance.tenantId,
  'role': instance.role,
  'email': instance.email,
  'created_at': instance.createdAt,
};
