// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be regenerated by build_runner

part of 'user_model.dart';

UserModel _$UserModelFromJson(Map<String, dynamic> json) => UserModel(
  name: json['name'] as String,
  username: json['username'] as String,
  email: json['email'] as String,
  tenantId: json['tenant_id'] as String,
  role: json['role'] as String,
);

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
  'name': instance.name,
  'username': instance.username,
  'email': instance.email,
  'tenant_id': instance.tenantId,
  'role': instance.role,
};
